// <auto-generated />
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(StakeholdersContext))]
    [Migration("20250723202622_AddedSeedForProfiles")]
    partial class AddedSeedForProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Moto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProfilePicureUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Biography = "Experienced tour guide with over 10 years of guiding tours in Europe.",
                            FirstName = "John",
                            LastName = "Doe",
                            Moto = "Discover the world with passion.",
                            ProfilePicureUrl = "https://example.com/profiles/johndoe.jpg",
                            UserId = 12345L
                        },
                        new
                        {
                            Id = 2L,
                            Biography = "Tourist looking for the best culinary experiences across the globe.",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Moto = "Eat, Travel, Enjoy.",
                            ProfilePicureUrl = "https://example.com/profiles/janesmith.jpg",
                            UserId = 12346L
                        },
                        new
                        {
                            Id = 3L,
                            Biography = "A passionate history buff who loves to show people hidden gems in ancient cities.",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Moto = "History lives through the stories we tell.",
                            ProfilePicureUrl = "https://example.com/profiles/alicejohnson.jpg",
                            UserId = 12347L
                        },
                        new
                        {
                            Id = 4L,
                            Biography = "Tourist looking to explore unique and off-the-beaten-path destinations.",
                            FirstName = "Bob",
                            LastName = "Williams",
                            Moto = "Explore the unexplored.",
                            ProfilePicureUrl = "https://example.com/profiles/bobwilliams.jpg",
                            UserId = 12348L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
